### ISSUE TITLE
Is it possible to change return the Promise object?

### ISSUE THREAD

**Issue by holyshared** [elliotf/mocha-mongoose#9]
I think that when you to return the Promise object, become better.
For example, will be as follows.

```nodejs
clearDB = require('mocha-mongoose')(dbURI) //Return promise object  
clearDB.then(function() {
  //do something
}).error(function(error) {
  //do something
})
```

What do you think?.

**Comment by elliotf** [comment]
I welcome pull requests!  I don't actually use this library anymore, so any help you can provide is welcome.  :)

**Comment by elliotf** [comment]
I'm going to go ahead and close this issue.  Please feel free to reopen or create a pull request.  Thank you!

**Comment by cellis** [comment]
In case anyone finds this, ( and @elliotf perhaps it could be in the readme ), I was able to get promises working with code like this:

```javascript
const Q = require('q') // or import Q from 'q';
const promise = Q.nfcall(clearDB);

// example
// Q.nfcall(clearDB).then(function() {
//  
//}).catch(function(err) { 
// handle err here
//});
```
Also works in jest 🎉
